/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Principal;

import Clases.Conexion;
import Clases.Pago;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Reymundo Tenorio
 */
public class PagoP extends javax.swing.JFrame {

    /**
     * Creates new form Estudiante
     */
    public PagoP() {
        
         try{
        this.setIconImage (new ImageIcon(getClass().getResource("/Imagenes/Pago.png")).getImage());
        }catch(NullPointerException ex){}
        
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        TabbedPane = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        PanelNuevo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JdFecha = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCuota = new javax.swing.JTextField();
        txtRevista = new javax.swing.JTextField();
        txtSuscriptor = new javax.swing.JTextField();
        txtNoCuotas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TabbedPane.setBackground(new java.awt.Color(0, 204, 204));
        TabbedPane.setColorDeBorde(new java.awt.Color(0, 204, 204));
        TabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabbedPaneMousePressed(evt);
            }
        });
        TabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneStateChanged(evt);
            }
        });

        PanelNuevo.setBackground(new java.awt.Color(0, 153, 204));
        PanelNuevo.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnsave.setMnemonic('g');
        btnsave.setText("Guardar");
        btnsave.setToolTipText("Guardar Estudiante");
        btnsave.setContentAreaFilled(false);
        btnsave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btncancel.setMnemonic('c');
        btncancel.setText("Cancelar");
        btncancel.setToolTipText("Cancelar / Salir");
        btncancel.setContentAreaFilled(false);
        btncancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel);

        PanelNuevo.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Nuevo Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(235, 235, 150));
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Suscriptor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. de Cuotas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de Pago");

        JdFecha.setDateFormatString("dd-MM-yyyy");
        JdFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Revista");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Monto de Cuota");

        txtCuota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCuota.setToolTipText("Ingrese Apellidos del Estudiante");
        txtCuota.setEnabled(false);
        txtCuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuotaKeyTyped(evt);
            }
        });

        txtRevista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRevista.setToolTipText("Ingrese Apellidos del Estudiante");
        txtRevista.setEnabled(false);
        txtRevista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRevistaKeyTyped(evt);
            }
        });

        txtSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSuscriptor.setToolTipText("Ingrese Apellidos del Estudiante");
        txtSuscriptor.setEnabled(false);
        txtSuscriptor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuscriptorKeyTyped(evt);
            }
        });

        txtNoCuotas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNoCuotas.setToolTipText("Ingrese Apellidos del Estudiante");
        txtNoCuotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoCuotasKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JdFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(txtCuota)
                    .addComponent(txtRevista)
                    .addComponent(txtSuscriptor)
                    .addComponent(txtNoCuotas))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuscriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        JdFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdFechaKeyTyped(evt);
            }
        });

        JdFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdFechaKeyReleased(evt);
            }
        });

        JdFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdFechaKeyPressed(evt);
            }
        });

        JdFecha.getDateEditor().getUiComponent().setToolTipText("Fecha de Suscripción");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 288;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(138, 289, 102, 315);
        jPanel6.add(jPanel3, gridBagConstraints);

        PanelNuevo.add(jPanel6, java.awt.BorderLayout.CENTER);

        TabbedPane.addTab("Agregar Pago", PanelNuevo);

        getContentPane().add(TabbedPane, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1209, 722));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private int ID_Suscripcion;    
    private SuscripcionP MP;
     private VerPagos VP;

    public void setVP(VerPagos VP) {
        this.VP = VP;
    }
   
    
    

    public void setMP(SuscripcionP MP) {
        this.MP = MP;
    }
    
   
   
    public void Datos(String Suscriptor, String Revista, String Cuota, String NoCuota, int ID_Suscripcion){
        
        txtCuota.setText(Cuota);
        txtRevista.setText(Revista);
        txtSuscriptor.setText(Suscriptor);
        this.ViejaCuota = Integer.parseInt(NoCuota);
        this.ID_Suscripcion = ID_Suscripcion;
        
    }

    public void  jdFechaKeyTyped(KeyEvent evt) {   
        
  char a = evt.getKeyChar();
        
 
    evt.consume();   
    Toolkit.getDefaultToolkit().beep();      
 
        }

    public void  jdFechaKeyPressed(KeyEvent evt) {   
    char a = evt.getKeyChar();
        
    evt.consume();   
    Toolkit.getDefaultToolkit().beep();      
 
        }
    
    public void  jdFechaKeyReleased(KeyEvent evt) {   
     char a = evt.getKeyChar();
        

    evt.consume();   
    Toolkit.getDefaultToolkit().beep();      
     
        }
  
    
 
    
    public static ResultSet resultado;

    private boolean Modify = false;

    public void setModify(boolean Modify) {
        this.Modify = Modify;
    }
    
    int ViejaCuota;
    
    public void Guardar (){
        
        
        
        int NoCuotas;  
        long Fecha = 0;
        String Cuotas;
        
        Cuotas = txtNoCuotas.getText().trim();
 
        
        if("".equals(Cuotas))  {
            JOptionPane.showMessageDialog(this,"Seleccione La Revista","Seleccione",JOptionPane.ERROR_MESSAGE);
            return;
           }
        
        int SumCuota = 0;
        
        try{
            
            resultado = Conexion.consulta("Select Sum(No_Cuotas) from pago where ID_Suscripcion = "+ID_Suscripcion);
            
            while(resultado.next()){
                SumCuota = resultado.getInt(1);
            }
            
        }catch(SQLException ex){
            
        }
        
        if(Modify==true){
            SumCuota=SumCuota+ViejaCuota;
        }
        
        int SC = 11-SumCuota;
       
    
        NoCuotas = Integer.parseInt(Cuotas);
        

          if(11==SumCuota){
              JOptionPane.showMessageDialog(this, "La Suscripción Ha Sido Pagada Por Completo","Pagada",JOptionPane.WARNING_MESSAGE);     
             return; 
          }
        
          if(SC<NoCuotas)  {
          JOptionPane.showMessageDialog(this, "El Número de Cuota a Pagar Excede La Cantidad Permitido","Exceso",JOptionPane.ERROR_MESSAGE);     
             return; 
         }
          
        if(NoCuotas>11){
             JOptionPane.showMessageDialog(this, "El Número de Cuota a Pagar Excede La Cantidad Permitido","Exceso",JOptionPane.ERROR_MESSAGE);     
             return; 
         }
          
         if(JdFecha.getDate()!=null){
            
             Date date = JdFecha.getDate();
             Fecha = date.getTime();
           
        }
  
         if(Modify == true){
             
             Pago.Actualizar_Pago(ID_Suscripcion, NoCuotas, Fecha);
             Modify = false;
             
         }
         else{

              
                Pago.Agregar_Pago(ID_Suscripcion, NoCuotas, Fecha);
         }
                CleanAll();
                DisableAll();
                
                dispose();

            
    }
    
    public void CleanAll(){
       txtNoCuotas.setText("1");
       txtCuota.setText("");
       txtRevista.setText("");
       txtSuscriptor.setText("");
       JdFecha.setDate(null);
    }
    
    public void EnableAll(){
   
        txtNoCuotas.setEnabled(true);
        JdFecha.setEnabled(true);
        btnsave.setEnabled(true);
        
    }
    
      public void DisableAll(){
        txtNoCuotas.setEnabled(false);
        JdFecha.setEnabled(false);
        btnsave.setEnabled(false);
        
    }
    

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        if(MP!=null){
        MP.setVisible(false);
        }
        if(VP!=null){
        VP.setVisible(false);
        }
          String Dia, Mes, Ano;

        Calendar c = new GregorianCalendar();

        Dia = Integer.toString(c.get(Calendar.DATE));
        Mes = Integer.toString(c.get(Calendar.MONTH)+1);
        Ano = Integer.toString(c.get(Calendar.YEAR));

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String strFecha =Dia+"-"+Mes+"-"+Ano ;
        Date Fecha;
        
        try {

            Fecha = sdf.parse(strFecha);

            JdFecha.setMaxSelectableDate(Fecha);
            JdFecha.setDate(Fecha);

        } catch (ParseException ex) {
        }
        
     
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    if(MP!=null){
        
        MP.setVisible(true);
        }  
    if(VP!=null){
        VP.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed


   
    
   
    private void TabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneStateChanged

    private void TabbedPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPaneMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneMousePressed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
if(MP!=null){
        MP.setVisible(true);
        }  
    if(VP!=null){
        VP.setVisible(true);
        }
       
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        Guardar();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtCuotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaKeyTyped
        char a = evt.getKeyChar();
        char c = evt.getKeyChar();

        double x=0;

        if("0".equals(txtCuota.getText())&&txtCuota.getCaretPosition()==1&&c!='.'&&!Character.isISOControl(c)){
            txtCuota.setText(txtCuota.getText()+".");
            //   return;
        }

        if (c == '.' && txtCuota.getText().contains(".")) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            return;
        }

        String x1 = "";
        if(Character.isDigit(c)||(Character.isISOControl(c)&&!"".equals(txtCuota.getText()))){
            x1 = txtCuota.getText();
        }
        if(Character.isDigit(c)||(c == '.')){
            x1 = txtCuota.getText().concat(String.valueOf(c));
        }

        if(!"".equals(x1)){
            x = Double.parseDouble(x1);
        }

        if ((!Character.isDigit(c)) && (!Character.isISOControl(c))
            && (c != '.')||x>99999999) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaKeyTyped

    private void txtRevistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRevistaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRevistaKeyTyped

    private void txtSuscriptorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuscriptorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuscriptorKeyTyped

    private void txtNoCuotasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoCuotasKeyTyped
char a  = evt.getKeyChar();

if(!Character.isDigit(a)&&!Character.isISOControl(a)){
    Toolkit.getDefaultToolkit().beep();
    evt.consume();
}

// TODO add your handling code here:
    }//GEN-LAST:event_txtNoCuotasKeyTyped

   
 
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PagoP().setVisible(true);
        });
}  
     
   

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JdFecha;
    private javax.swing.JPanel PanelNuevo;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader TabbedPane;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtNoCuotas;
    private javax.swing.JTextField txtRevista;
    private javax.swing.JTextField txtSuscriptor;
    // End of variables declaration//GEN-END:variables
}
