/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Principal;

import Clases.Conexion;
import Clases.Suscripcion;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Reymundo Tenorio
 */
public class SuscripcionP extends javax.swing.JFrame {

    /**
     * Creates new form Estudiante
     */
    public SuscripcionP() {
        
         try{
        this.setIconImage (new ImageIcon(getClass().getResource("/Imagenes/Suscripcion.png")).getImage());
        }catch(NullPointerException ex){}
        
        initComponents();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        PopupMenu = new javax.swing.JPopupMenu();
        MnPago = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MnItemModificar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MnItemActDes = new javax.swing.JMenuItem();
        TabbedPane = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        PanelNuevo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JdFecha = new com.toedter.calendar.JDateChooser();
        cmbRevista = new javax.swing.JComboBox();
        cmbSuscriptor = new javax.swing.JComboBox();
        PanelVer = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbbusc = new javax.swing.JComboBox();
        btnbuscar = new javax.swing.JButton();
        txtbusc = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnPagar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        btnmodify = new javax.swing.JButton();
        btncancel3 = new javax.swing.JButton();

        MnPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PayIcon.png"))); // NOI18N
        MnPago.setMnemonic('P');
        MnPago.setText("Pagar");
        MnPago.setToolTipText("Pagar Suscripción");
        MnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPagoActionPerformed(evt);
            }
        });
        PopupMenu.add(MnPago);
        PopupMenu.add(jSeparator2);

        MnItemModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ModificarIcon.png"))); // NOI18N
        MnItemModificar.setMnemonic('m');
        MnItemModificar.setText("Modificar");
        MnItemModificar.setToolTipText("Modificar Suscripción");
        MnItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemModificarActionPerformed(evt);
            }
        });
        PopupMenu.add(MnItemModificar);
        PopupMenu.add(jSeparator1);

        MnItemActDes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ActivarIcon.png"))); // NOI18N
        MnItemActDes.setMnemonic('a');
        MnItemActDes.setText("Activar");
        MnItemActDes.setToolTipText("Activar Suscripción");
        MnItemActDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemActDesActionPerformed(evt);
            }
        });
        PopupMenu.add(MnItemActDes);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Revista");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TabbedPane.setBackground(new java.awt.Color(0, 204, 204));
        TabbedPane.setColorDeBorde(new java.awt.Color(0, 204, 204));
        TabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabbedPaneMousePressed(evt);
            }
        });
        TabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneStateChanged(evt);
            }
        });

        PanelNuevo.setBackground(new java.awt.Color(0, 153, 204));
        PanelNuevo.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        btnnew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnnew.setForeground(new java.awt.Color(255, 255, 255));
        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo_1.png"))); // NOI18N
        btnnew.setMnemonic('n');
        btnnew.setText("Nuevo");
        btnnew.setToolTipText("Ingresar Nuevo Estudiante");
        btnnew.setContentAreaFilled(false);
        btnnew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        jPanel1.add(btnnew);

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnsave.setMnemonic('g');
        btnsave.setText("Guardar");
        btnsave.setToolTipText("Guardar Estudiante");
        btnsave.setContentAreaFilled(false);
        btnsave.setEnabled(false);
        btnsave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btncancel.setMnemonic('c');
        btncancel.setText("Cancelar");
        btncancel.setToolTipText("Cancelar / Salir");
        btncancel.setContentAreaFilled(false);
        btncancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel);

        PanelNuevo.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Nueva Suscripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(235, 235, 150));
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Suscriptor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Revista");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha");

        JdFecha.setDateFormatString("dd-MM-yyyy");
        JdFecha.setEnabled(false);
        JdFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cmbRevista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbRevista.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>" }));
        cmbRevista.setEnabled(false);

        cmbSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSuscriptor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>" }));
        cmbSuscriptor.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSuscriptor, 0, 301, Short.MAX_VALUE)
                    .addComponent(JdFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbRevista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSuscriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JdFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JdFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdFechaKeyTyped(evt);
            }
        });

        JdFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdFechaKeyReleased(evt);
            }
        });

        JdFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdFechaKeyPressed(evt);
            }
        });

        JdFecha.getDateEditor().getUiComponent().setToolTipText("Fecha de Suscripción");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 274;
        gridBagConstraints.ipady = 138;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(132, 289, 107, 315);
        jPanel6.add(jPanel3, gridBagConstraints);

        PanelNuevo.add(jPanel6, java.awt.BorderLayout.CENTER);

        TabbedPane.addTab("Nueva Suscripción", PanelNuevo);

        PanelVer.setBackground(new java.awt.Color(235, 235, 150));
        PanelVer.setLayout(new javax.swing.BoxLayout(PanelVer, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setBackground(new java.awt.Color(0, 153, 204));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(235, 235, 150));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Suscripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar Por: ");

        cmbbusc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbbusc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No.", "Fecha", "Nombres Suscriptor", "Apellidos Suscriptor", "Título Revista", "Estado" }));
        cmbbusc.setToolTipText("Buscar Por:");

        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BuscarIcon.png"))); // NOI18N
        btnbuscar.setMnemonic('b');
        btnbuscar.setText("Buscar");
        btnbuscar.setToolTipText("Buscar Estudiante");
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtbusc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscKeyReleased(evt);
            }
        });
        /*txtbusc = new AutoComplete.AutoCompletar();

        ((AutoCompletar)txtbusc).setDesplegable(new DesplegableJPopUPMenu(txtbusc));

        ModeloAutoCompletar modelo1 = new ModeloVendNames();

        ((AutoCompletar)txtbusc).setModelo(modelo1);
        ((AutoCompletar)txtbusc).getDesplegable().setForeground(new Color(102,153,255));

        ((AutoCompletar)txtbusc).addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscTyped(evt);
            }
        });

        ((AutoCompletar)txtbusc).setToolTipText("Ingresar Dato a Buscar");*/

        btnMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TodosIcon.png"))); // NOI18N
        btnMostrar.setMnemonic('b');
        btnMostrar.setText("Ver Todos");
        btnMostrar.setToolTipText("Mostrar Todos Los Estudiantes");
        btnMostrar.setContentAreaFilled(false);
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbbusc, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtbusc, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbusc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar)
                    .addComponent(txtbusc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar))
                .addContainerGap())
        );

        jPanel7.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setToolTipText("Lista de Estudiantes");
        jTable1.setComponentPopupMenu(PopupMenu);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(jTable1);

        jPanel7.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));

        btnPagar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pay.png"))); // NOI18N
        btnPagar.setMnemonic('A');
        btnPagar.setText("Pagar");
        btnPagar.setToolTipText("Activar Estudiante(s) Seleccionado(s)");
        btnPagar.setContentAreaFilled(false);
        btnPagar.setEnabled(false);
        btnPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPagar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnPagarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnPagarFocusLost(evt);
            }
        });
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel5.add(btnPagar);

        btnActivar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActivar.setForeground(new java.awt.Color(255, 255, 255));
        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Activar.png"))); // NOI18N
        btnActivar.setMnemonic('A');
        btnActivar.setText("Activar");
        btnActivar.setToolTipText("Activar Estudiante(s) Seleccionado(s)");
        btnActivar.setContentAreaFilled(false);
        btnActivar.setEnabled(false);
        btnActivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActivar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnActivarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnActivarFocusLost(evt);
            }
        });
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        jPanel5.add(btnActivar);

        btnDesactivar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDesactivar.setForeground(new java.awt.Color(255, 255, 255));
        btnDesactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Desactivar.png"))); // NOI18N
        btnDesactivar.setMnemonic('d');
        btnDesactivar.setText("Desactivar");
        btnDesactivar.setToolTipText("Desactivar Estudiante(s) Seleccionado(s)");
        btnDesactivar.setContentAreaFilled(false);
        btnDesactivar.setEnabled(false);
        btnDesactivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesactivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDesactivar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnDesactivarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnDesactivarFocusLost(evt);
            }
        });
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });
        jPanel5.add(btnDesactivar);

        btnmodify.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnmodify.setForeground(new java.awt.Color(255, 255, 255));
        btnmodify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnmodify.setMnemonic('o');
        btnmodify.setText("Modificar");
        btnmodify.setToolTipText("Modificar Estudiante Seleccionado");
        btnmodify.setContentAreaFilled(false);
        btnmodify.setEnabled(false);
        btnmodify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodify.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmodify.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnmodifyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnmodifyFocusLost(evt);
            }
        });
        btnmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifyActionPerformed(evt);
            }
        });
        jPanel5.add(btnmodify);

        btncancel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel3.setForeground(new java.awt.Color(255, 255, 255));
        btncancel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btncancel3.setMnemonic('c');
        btncancel3.setText("Cancelar");
        btncancel3.setToolTipText("Cancelar / Salir");
        btncancel3.setContentAreaFilled(false);
        btncancel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel3ActionPerformed(evt);
            }
        });
        jPanel5.add(btncancel3);

        jPanel7.add(jPanel5, java.awt.BorderLayout.SOUTH);

        PanelVer.add(jPanel7);

        TabbedPane.addTab("Ver Suscripciones", PanelVer);

        getContentPane().add(TabbedPane, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1209, 722));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private int ID_Suscripcion;
    private boolean Modify;
    private MenuPrincipal MP;
   

    public void  jdFechaKeyTyped(KeyEvent evt) {   
        
  char a = evt.getKeyChar();
        
 
    evt.consume();   
    Toolkit.getDefaultToolkit().beep();      
 
        }

    public void  jdFechaKeyPressed(KeyEvent evt) {   
    char a = evt.getKeyChar();
        
    evt.consume();   
    Toolkit.getDefaultToolkit().beep();      
 
        }
    
    public void  jdFechaKeyReleased(KeyEvent evt) {   
     char a = evt.getKeyChar();
        

    evt.consume();   
    Toolkit.getDefaultToolkit().beep();      
     
        }
  
    
    public void setMP(MenuPrincipal MP) {
        this.MP = MP;
    }
    
    
    public static ResultSet resultado;

    
    public void Guardar (){
        
        
        
        int Suscriptor, Revista;  
        long Fecha = 0;
        String Sus, Rev;
        
      Sus = (String) cmbSuscriptor.getSelectedItem();
      Rev = (String) cmbRevista.getSelectedItem();
  
      Suscriptor = cmbSuscriptor.getSelectedIndex();
      Revista = cmbRevista.getSelectedIndex();
       
          if("<Seleccione>".equals(Sus))  {
            JOptionPane.showMessageDialog(this,"Seleccione al Suscriptor","Seleccione",JOptionPane.ERROR_MESSAGE);
            return;
           }
        
        if("<Seleccione>".equals(Rev))  {
            JOptionPane.showMessageDialog(this,"Seleccione La Revista","Seleccione",JOptionPane.ERROR_MESSAGE);
            return;
           }
    
          
         if(JdFecha.getDate()!=null){
            
             Date date = JdFecha.getDate();
             Fecha = date.getTime();
           
        }
  
         int ID_S = ID_Suscriptor [Suscriptor];
         int ID_R = ID_Revista [Revista];

            if(Modify==true){

                int ID = ID_Suscripcion;
           
             Suscripcion.Actualizar_Suscripcion(ID, ID_S, ID_R, Fecha);
                
                ActualizarTabla();
                CleanAll();
                DisableAll();
                Modify = false;
            }
            else{

              
              Suscripcion.Agregar_Suscripcion(ID_S, ID_R, Fecha);
                
                
                ActualizarTabla();
                CleanAll();
                DisableAll();

            }
    }
    
    public void CleanAll(){
       cmbRevista.setSelectedIndex(0);
       cmbSuscriptor.setSelectedIndex(0);
       JdFecha.setDate(null);
    }
    
    public void EnableAll(){
        cmbRevista.setEnabled(true);
        cmbSuscriptor.setEnabled(true);
        JdFecha.setEnabled(true);
        btnsave.setEnabled(true);
        
    }
    
      public void DisableAll(){
        cmbRevista.setEnabled(false);
        cmbSuscriptor.setEnabled(false);
        JdFecha.setEnabled(false);
        btnsave.setEnabled(false);
        
    }
    
    
      
  
    
   
    
   public void ActualizarTabla(){
        
        
       model.setRowCount(0);
       jTable1.setModel(model);
       
      
        try{
            
        
        resultado = Conexion.consulta("Select * from suscripcionv");

        
       
     
       while (resultado.next())
       {     
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
    }
       
       jTable1.setModel(model);
    
   
//        jTable1.getColumnModel().getColumn( 10 ).setCellEditor( new Celda_CheckBox() );
//        //para pintar la columna con el CheckBox en la tabla, en este caso, la primera columna
//        jTable1.getColumnModel().getColumn( 10 ).setCellRenderer(new Render_CheckBox());      

        
    }   catch (SQLException ex) {
      JOptionPane.showMessageDialog(null,ex.getMessage()); 
    }
        
          
    }
   
   

   
    
    public void Buscar(){
     
        int index = cmbbusc.getSelectedIndex()+1;

        switch(index){

            case 1:

            try{
                model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where No = '"+Buscar+"'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"No. de Suscripción No Encontrado");
            }

            break;
                
                case 2:
                
                  try{
                   
                model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Fecha = '"+Buscar+"'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Estado de La Suscripción No Encontrado");
            }
            

            break;

            case 3:
                
                
            try{
              
                  model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Nombres = '"+Buscar+"'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }


            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Nombres del Suscriptor No Encontrado");
            }

            break;
                
            case 4:
                
            try{
                model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Apellidos = '"+Buscar+"'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Apellidos del Suscriptor No Encontrado");
            }
          
            break;
           
            case 5:
                
                  try{
                   
                  model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Titulo = '"+Buscar+"'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Título de La Revista No Encontrado");
            }
            

            break;
            
            case 6:
                
                  try{
                   
                model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Estado = '"+Buscar+"'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Estado de La Suscripción No Encontrado");
            }
            

            break;
            
       
       
            default:

            break;

          
        
        }
        
        ReiniciarTabla();
        jTable1.setModel(model);
        
        
    }
    
    
    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        Buscar();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtbuscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscKeyReleased
        int index = cmbbusc.getSelectedIndex()+1;

        switch(index){

          
              case 1:

            try{
                model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where No like '%"+Buscar+"%'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"No. de Suscripción No Encontrado");
            }

            break;
                
                case 2:
                
                  try{
                   
                model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Fecha like '%"+Buscar+"%'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Estado de La Suscripción No Encontrado");
            }
            

            break;

            case 3:
                
                
            try{
              
                  model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Nombres like '%"+Buscar+"%'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }


            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Nombres del Suscriptor No Encontrado");
            }

            break;
                
            case 4:
                
            try{
                model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Apellidos like '%"+Buscar+"%'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Apellidos del Suscriptor No Encontrado");
            }
          
            break;
           
            case 5:
                
                  try{
                   
                  model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Titulo like '%"+Buscar+"%'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Título de La Revista No Encontrado");
            }
            

            break;
            
            case 6:
                
                  try{
                   
                model.setRowCount(0);
                String Buscar = txtbusc.getText();
                resultado = Conexion.consulta("Select * from suscripcionv where Estado like '%"+Buscar+"%'");

                while (resultado.next())
                {
              
              Object [] Datos = new Object [7]; 

              Datos [0]= false;
              Datos [1]= String.valueOf(resultado.getInt(1));    
              Datos [2]= String.valueOf(resultado.getDate(2));
              Datos [3]= resultado.getString(3);
              Datos [4]= resultado.getString(4);
              Datos [5]= resultado.getString(5);
              Datos [6] = resultado.getString(6);
              
              model.addRow(Datos);  
   
                }

                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Estado de La Suscripción No Encontrado");
            }
            

            break;
            
       
       
            default:

            break;

                    
        
        }
        ReiniciarTabla();
        jTable1.setModel(model);
        
                // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscKeyReleased

    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      ActivarBotones();
 
          
     
int fila = jTable1.getSelectedRow();

if(fila != -1){

String Estado = ((String)this.jTable1.getModel().getValueAt(fila, 6));
 
 if("Inactivo".equalsIgnoreCase(Estado)){
      
MnItemActDes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ActivarIcon.png"))); // NOI18N

MnItemActDes.setMnemonic('a');

MnItemActDes.setText("Activar");

MnItemActDes.setToolTipText("Activar Suscripción");

    }
 if("Activo".equalsIgnoreCase(Estado)){
    
MnItemActDes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DesactivarIcon.png"))); // NOI18N

MnItemActDes.setMnemonic('a');

MnItemActDes.setText("Desactivar");

MnItemActDes.setToolTipText("Desactivar Suscripción");
}

}

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        
  ActivarBotones(); // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusLost

    public void ActivarDesactivarSuscripcion(){
        int fila = jTable1.getSelectedRow();

        int ID;
        String Nombre;
        int v=JOptionPane.NO_OPTION;
        String Estado;
        String Apellido;
        String Revista;

        if (fila > -1){
            
            

            ID= Integer.parseInt(this.jTable1.getModel().getValueAt(fila, 1).toString());
            Nombre=((String)this.jTable1.getModel().getValueAt(fila, 3));
            Apellido = ((String)this.jTable1.getModel().getValueAt(fila, 4));
            Revista = ((String)this.jTable1.getModel().getValueAt(fila, 5));
            Estado = ((String)this.jTable1.getModel().getValueAt(fila, 6));

           
            
            if("Activo".equalsIgnoreCase(Estado)){
                
                v= JOptionPane.showConfirmDialog(this, "Está Seguro Que Desea Desactivar La Suscripción de "+Nombre.trim()+" "+
                        Apellido.trim()+" Con La Revista "+Revista+"?", "Confirmación", JOptionPane.YES_NO_OPTION);
            }
            if("Inactivo".equalsIgnoreCase(Estado)){
             
                v= JOptionPane.showConfirmDialog(this, "Está Seguro Que Desea Activar La Suscripción de "+Nombre.trim()+" "+
                        Apellido.trim()+" Con La Revista "+Revista+"?", "Confirmación", JOptionPane.YES_NO_OPTION);
            }

            if(v==JOptionPane.YES_OPTION){

                
                Suscripcion.Activar_Desactivar_Suscripcion(ID);
               
                ActualizarTabla();
            }
        }

        else{

            JOptionPane.showMessageDialog(this, "Seleccione Una Suscripción a Activar/Desactivar", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }
    
    
     public void ActivarSuscripcion(){
     

        int ID;
        int v;
        boolean Flag;
      

           
          
//            if("Activo".equalsIgnoreCase(Estado)){
//                
//                v= JOptionPane.showConfirmDialog(this, "Está Seguro Que Desea Desactivar Estudiante(s) ?", "Confirmación", JOptionPane.YES_NO_OPTION);
//            }
            
             
             v= JOptionPane.showConfirmDialog(this, "Está Seguro Que Desea Activar Suscripción(es) ?", "Confirmación", JOptionPane.YES_NO_OPTION);
            
            if(v==JOptionPane.YES_OPTION){

                 
        for(int i=0; i<jTable1.getRowCount();i++){
            
            
            Flag = (boolean) this.jTable1.getModel().getValueAt(i, 0);
      
         if(Flag == true){
               ID= Integer.parseInt(this.jTable1.getModel().getValueAt(i, 1).toString());
      
              Suscripcion.Activar_Suscripcion(ID);
         }
               
            }
         JOptionPane.showMessageDialog(this, "Suscripción(es) Activada(s) Con Éxito", "Activado(s) Con Éxito", JOptionPane.INFORMATION_MESSAGE);

        }

//        if(jTable1.getSelectedRow() == -1){
//
//            JOptionPane.showMessageDialog(this, "Seleccione Estudiante(s) a Activar", "Error", JOptionPane.ERROR_MESSAGE);
//
//        }
       
         ActualizarTabla();
    }
    
     
      public void DesactivarSuscripcion(){
     

        int ID;
        int v;
        boolean Flag;
      

           
          
                    
   v= JOptionPane.showConfirmDialog(this, "Está Seguro Que Desea Desactivar Suscripción(es) ?", "Confirmación", JOptionPane.YES_NO_OPTION);
           
            
             
          
            if(v==JOptionPane.YES_OPTION){

                 
        for(int i=0; i<jTable1.getRowCount();i++){
            
            
            Flag = (boolean) this.jTable1.getModel().getValueAt(i, 0);
      
         if(Flag == true){
               ID= Integer.parseInt(this.jTable1.getModel().getValueAt(i, 1).toString());
      
              Suscripcion.Desactivar_Suscripcion(ID);
         }
               
            }
        
        JOptionPane.showMessageDialog(this, "Suscripción(es) Desactivada(s) Con Éxito", "Desactivado(s) Con Éxito", JOptionPane.INFORMATION_MESSAGE);

        }

//        if(jTable1.getSelectedRow() == -1){
//
//            JOptionPane.showMessageDialog(this, "Seleccione Estudiante(s) a Desactivar", "Error", JOptionPane.ERROR_MESSAGE);
//
//        }
        
         ActualizarTabla();
    }
      
      
    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed

       
         ActivarBotones();
         
         ActivarSuscripcion();
         ReiniciarTabla();
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnActivarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnActivarFocusGained
        
        ActivarBotones();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnActivarFocusGained

    public void Modificar(){
        
      ActivarBotones();
      
      
      
        int fila = jTable1.getSelectedRow();

        int ID;
        String Nombres = null, Apellidos = null, Suscriptor = null, Revista = null;  
        
        if (fila > -1){

            ID= Integer.parseInt(this.jTable1.getModel().getValueAt(fila, 1).toString()); 
           
  
            CleanAll();
            EnableAll();

            java.sql.Date Fecha = null;
            
        try{
            
            resultado = Conexion.consulta("Select Nombres, Apellidos, Titulo, Fecha from suscripcionv where No = "+ID);
            
            
            while (resultado.next()){
                Nombres = resultado.getString(1).trim();
                Apellidos = resultado.getString(2).trim();
                Revista = resultado.getString(3).trim();
                Fecha = resultado.getDate(4);
            }
        }catch(SQLException ex){
        } 
        
        Suscriptor = Nombres.concat(" ").concat(Apellidos);
        ID_Suscripcion = ID;
        cmbRevista.setSelectedItem(Revista);
        cmbSuscriptor.setSelectedItem(Suscriptor);
        
       long F = Fecha.getTime();
       Date Fe = new Date(F);
       
       JdFecha.setDate(Fe);
     

        
       
       

            TabbedPane.setSelectedComponent(PanelNuevo);
            Modify=true;

        }

        else{

            JOptionPane.showMessageDialog(this, "Seleccione Una Suscripción a Modificar", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }
    
    private void btnmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifyActionPerformed
Modificar();
    }//GEN-LAST:event_btnmodifyActionPerformed

    private void btnmodifyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnmodifyFocusGained
       ActivarBotones();
       
// TODO add your handling code here:
    }//GEN-LAST:event_btnmodifyFocusGained

    private void btncancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel3ActionPerformed
        MP.setVisible(true);  
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncancel3ActionPerformed

    private void TabbedPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPaneMousePressed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneMousePressed

    private void TabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneStateChanged
       
         // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneStateChanged

    private int [] ID_Revista;
    private int [] ID_Suscriptor;
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

          String Dia, Mes, Ano;

        Calendar c = new GregorianCalendar();

        Dia = Integer.toString(c.get(Calendar.DATE));
        Mes = Integer.toString(c.get(Calendar.MONTH)+1);
        Ano = Integer.toString(c.get(Calendar.YEAR));

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String strFecha =Dia+"-"+Mes+"-"+Ano ;
        Date Fecha;
        
        try {

            Fecha = sdf.parse(strFecha);

            JdFecha.setMaxSelectableDate(Fecha);
            JdFecha.setDate(Fecha);

        } catch (ParseException ex) {
        }
        
     int ID_RevMax = 0, ID_SuscMax = 0;
     
     try{
         
     resultado = Conexion.consulta("Select Max(ID_Revista) from revista");
         
     while(resultado.next()){
         ID_RevMax = resultado.getInt(1);
     }
     }catch(SQLException ex){
         
     }
     
      try{
         
     resultado = Conexion.consulta("Select Max(ID_Suscriptor) from suscriptor");
         
     while(resultado.next()){
         ID_SuscMax = resultado.getInt(1);
     }
     }catch(SQLException ex){
         
     }
        
      
      ID_RevMax++;
      ID_SuscMax++;
      ID_Revista = new int[ID_RevMax];
      ID_Suscriptor = new int[ID_SuscMax];

       
      ID_Revista [0] = 0; 
      ID_Suscriptor [0] = 0; 
      
     
      
      int i = 1;
      
      try{
         
     resultado = Conexion.consulta("Select ID_Revista, Titulo from revista");
         
     while(resultado.next()){
         ID_Revista [i] = resultado.getInt(1);
         cmbRevista.addItem(resultado.getString(2));
         i++;
     }
     }catch(SQLException ex){
         
     }
       
      
      int j = 1;
      String Nombres, Apellidos;
      try{
         
     resultado = Conexion.consulta("Select ID_Suscriptor, Nombres, Apellidos from suscriptor");
         
     while(resultado.next()){
         ID_Suscriptor [j] = resultado.getInt(1);
         
         Nombres = resultado.getString(2).trim();
         Apellidos = resultado.getString(3).trim();
         cmbSuscriptor.addItem(Nombres+" "+Apellidos);
         j++;
     }
     }catch(SQLException ex){
         
     }
        
     ReiniciarTabla();
     
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    MP.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    
    public void ActivarBotones(){
         
        String Estado;

   
      boolean Checkbox = false;
      
      for(int j=0; j<jTable1.getRowCount(); j++){
        
          Checkbox = (boolean) jTable1.getValueAt(j, 0);
          
          if(Checkbox == true){      
            
             btnActivar.setEnabled(true);
             btnDesactivar.setEnabled(true);
             
              break;
          }
       }
      
      
       
      int Fila = jTable1.getSelectedRow();
        
      if(Checkbox == false){
      
           btnActivar.setEnabled(false);
           btnDesactivar.setEnabled(false);

        if (Fila > -1){

            btnmodify.setEnabled(true);
            

            Estado = ((String)this.jTable1.getModel().getValueAt(Fila, 6));
     

            if("Activo".equalsIgnoreCase(Estado)){
                btnPagar.setEnabled(true);
                            }
            if("Inactivo".equalsIgnoreCase(Estado)){
                btnPagar.setEnabled(false);
            }
   
        }
        else{
            btnmodify.setEnabled(false);
    
        }  
      }

      
        if (Fila > -1){
              btnmodify.setEnabled(true);
        }
        else{
              btnmodify.setEnabled(false);
        }
    }
    
    private void btnActivarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnActivarFocusLost
 
 ActivarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnActivarFocusLost

    private void btnmodifyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnmodifyFocusLost
  ActivarBotones();    // TODO add your handling code here:
    }//GEN-LAST:event_btnmodifyFocusLost

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
  ActivarBotones();     // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
     ActivarBotones();// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed

        MP.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        Guardar();
        ReiniciarTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed

        EnableAll();
        CleanAll();
        
          String Dia, Mes, Ano;

        Calendar c = new GregorianCalendar();

        Dia = Integer.toString(c.get(Calendar.DATE));
        Mes = Integer.toString(c.get(Calendar.MONTH)+1);
        Ano = Integer.toString(c.get(Calendar.YEAR));

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String strFecha =Dia+"-"+Mes+"-"+Ano ;
        Date Fecha;
        
        try {

            Fecha = sdf.parse(strFecha);

            JdFecha.setDate(Fecha);

        } catch (ParseException ex) {
        }
        
    }//GEN-LAST:event_btnnewActionPerformed

   
    
    private void MnItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemModificarActionPerformed
Modificar();      // TODO add your handling code here:
    }//GEN-LAST:event_MnItemModificarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
ActivarBotones();
DesactivarSuscripcion();
ReiniciarTabla();// TODO add your handling code here:
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnDesactivarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDesactivarFocusGained
   ActivarBotones();     // TODO add your handling code here:
    }//GEN-LAST:event_btnDesactivarFocusGained

    private void btnDesactivarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDesactivarFocusLost
    ActivarBotones();    // TODO add your handling code here:
    }//GEN-LAST:event_btnDesactivarFocusLost

   public void ReiniciarTabla(){
        
        Object [] Titulo = {"","No.", "Fecha", "Nombres Suscriptor", "Apellidos Suscriptor",
            "Revista", "Estado"};
        
        model.setColumnIdentifiers(Titulo);
                
        
        this.jTable1.setModel(model);
        
        
        jTable1.setDefaultRenderer(Object.class, new FormatoTablaSuscripcion());
      
       
        CheckBoxHeader();  
        ActualizarTabla();     
    }
    
    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed

        ReiniciarTabla();
      
               // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void MnItemActDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemActDesActionPerformed
ActivarDesactivarSuscripcion();        // TODO add your handling code here:
    }//GEN-LAST:event_MnItemActDesActionPerformed

    public void Pagar(){
         int Fila = jTable1.getSelectedRow();
        
  String Suscriptor, Nombres, Apellidos, Revista, ID_Sus;
  int ID;
  double Cuota = 0;

        if (Fila > -1){

            btnmodify.setEnabled(true);
            
            ID_Sus = ((String)this.jTable1.getModel().getValueAt(Fila, 1));
            Nombres = ((String)this.jTable1.getModel().getValueAt(Fila, 3));
            Apellidos = ((String)this.jTable1.getModel().getValueAt(Fila, 4));
            Revista = ((String)this.jTable1.getModel().getValueAt(Fila, 5));
            
            Suscriptor = Nombres.trim().concat(" ")+ Apellidos.trim();
            ID = Integer.parseInt(ID_Sus);
            
            try{
                
                resultado = Conexion.consulta("Select Cuota from cuotav where ID_Suscripcion = "+ID);
                
                while(resultado.next()){
                    
                    Cuota = resultado.getDouble(1);
                }
                
            }catch(SQLException ex){
                
            }
            
            PagoP Pay = new PagoP();
            Pay.setMP(this);
            Pay.Datos(Suscriptor, Revista, String.valueOf(Cuota),"0", ID);
            Pay.setVisible(true);
            
       
        }
    

    }
    
    private void MnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPagoActionPerformed
Pagar();        
// TODO add your handling code here:
    }//GEN-LAST:event_MnPagoActionPerformed

    private void btnPagarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPagarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarFocusGained

    private void btnPagarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPagarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarFocusLost

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
Pagar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarActionPerformed

    
    
    DefaultTableModel model = new DefaultTableModel() {

        
        
    Class[] types = new Class [] {
  
        java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, 
        java.lang.String.class, java.lang.String.class, java.lang.String.class
    };
 

    @Override
    public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
    }

  

    @Override
    public boolean isCellEditable(int row, int column) {
    
     if(column == 0){
            return true;
        }else{
            return false;
    }
    
    }
};
    
    
    
    
     public class FormatoTablaSuscripcion extends DefaultTableCellRenderer
{
 @Override
 public Component getTableCellRendererComponent
 (JTable table, Object value, boolean selected, boolean focused, int row, int column)
 {
   
     
  
  if(String.valueOf(table.getValueAt(row,6)).equalsIgnoreCase("Inactivo"))  {
      setForeground(Color.RED);   
  }
  else { 
      
          setForeground(Color.BLACK);
      
   }
  
   if((boolean) table.getValueAt(row,0) == true)  {
      
       setBackground(new Color(0,204,204));
  }
   else{
        setBackground(new Color(255,255,255));
      
   }
   
   
 super.getTableCellRendererComponent(table, value, selected, focused, row, column);
 return this;
 }
 }
     
       
   
     
 public class CheckBoxHeader extends JCheckBox  implements TableCellRenderer, MouseListener {  
 
  protected CheckBoxHeader rendererComponent;  
  protected int column;  


  protected boolean mousePressed = false;  
  
  public CheckBoxHeader(ItemListener itemListener) {  
    rendererComponent = this;  
    rendererComponent.addItemListener(itemListener);
    
  }  
  @Override
  public Component getTableCellRendererComponent(  
      JTable table, Object value,  
      boolean isSelected, boolean hasFocus, int row, int column) {  
    if (table != null) {  
      JTableHeader header = table.getTableHeader();  
      if (header != null) {  
        rendererComponent.setForeground(header.getForeground());  
        rendererComponent.setBackground(header.getBackground());  
        rendererComponent.setFont(header.getFont());  
        header.addMouseListener(rendererComponent);  
      }  
    }  
    setColumn(column);  
    rendererComponent.setText("Selecc. Todo");  
    setBorder(UIManager.getBorder("TableHeader.cellBorder"));  
    return rendererComponent;  
  }  
  protected void setColumn(int column) {  
    this.column = column;  
  }  
  public int getColumn() {  
    return column;  
  }  
  
  protected void handleClickEvent(MouseEvent e) {  
    if (mousePressed) {  
      mousePressed=false;  
      JTableHeader header = (JTableHeader)(e.getSource());  
      JTable tableView = header.getTable();  
      TableColumnModel columnModel = tableView.getColumnModel();  
      int viewColumn = columnModel.getColumnIndexAtX(e.getX());  
      int columna = tableView.convertColumnIndexToModel(viewColumn);  
   
      if (columna != -1 && viewColumn == this.column && e.getClickCount() == 1 
              && e.getButton() == MouseEvent.BUTTON1) {  
          doClick();
      }  
    }  
  } 
  
  @Override
  public void mouseClicked(MouseEvent e) {  
    handleClickEvent(e);  
    ((JTableHeader)e.getSource()).repaint();  
  }  
  @Override
  public void mousePressed(MouseEvent e) {  
    mousePressed = true;  
  }  
  @Override
  public void mouseReleased(MouseEvent e) {  
  }  
  @Override
  public void mouseEntered(MouseEvent e) {  
  }  
  @Override
  public void mouseExited(MouseEvent e) {  
  }  
    }  

 public void CheckBoxHeader()  
  {  
   
    TableColumn tc = jTable1.getColumnModel().getColumn(0);  //No Columna
    tc.setCellEditor(jTable1.getDefaultEditor(Boolean.class));  
    tc.setCellRenderer(jTable1.getDefaultRenderer(Boolean.class));  
    tc.setHeaderRenderer(new CheckBoxHeader(new MyItemListener()));  
    
   
  }  
  class MyItemListener implements ItemListener  
  {  
    @Override
    public void itemStateChanged(ItemEvent e) {  
      Object source = e.getSource();  
      if (source instanceof AbstractButton == false) return;  
      boolean checked = e.getStateChange() == ItemEvent.SELECTED;  
      for(int x = 0, y = jTable1.getRowCount(); x < y; x++)  
      {    
        jTable1.setValueAt(checked,x,0); 
        ActivarBotones();//No Columna
      }  
    }  
  }  
 
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SuscripcionP().setVisible(true);
        });
}  
     
   

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JdFecha;
    private javax.swing.JMenuItem MnItemActDes;
    private javax.swing.JMenuItem MnItemModificar;
    private javax.swing.JMenuItem MnPago;
    private javax.swing.JPanel PanelNuevo;
    private javax.swing.JPanel PanelVer;
    private javax.swing.JPopupMenu PopupMenu;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader TabbedPane;
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncancel3;
    private javax.swing.JButton btnmodify;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbRevista;
    private javax.swing.JComboBox cmbSuscriptor;
    private javax.swing.JComboBox cmbbusc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbusc;
    // End of variables declaration//GEN-END:variables
}
